### ISSUE TITLE
Test project build error when installing via VPM

### ISSUE THREAD

**Issue by Zerg17** [RGBCube/v-color#2]
When building any test example, I get an error:
```
C:\Users\zerg17\.vmodules\rgbcube\color\test.v is defined as module `main`
    1 | import rgbcube.color
      | ~~~~~~~~~~~~~~~~~~~~
```
The installation was performed by the command "v install RGBCube.color"

**Comment by RGBCube** [comment]
The library currently doesn't work because of some compiler bugs:
https://github.com/vlang/v/issues/16473
https://github.com/vlang/v/issues/16496
I am waiting for those to be resolved, then it should work in theory

**Comment by RGBCube** [comment]
Also, will fix this asap

**Comment by Zerg17** [comment]
Yes, there is such a problem. But there are a few more errors in the library and one in the example.
```
C:/Users/zerg17/.vmodules/rgbcube/color/src/paintbrush.v:25:13: error: undefined ident: `disabled`
   23 |         bg: p.bg
   24 |         styles: p.styles
   25 |         disabled: disabled
      |                   ~~~~~~~~
   26 |     }
   27 | }
```
Solution: Fix line 25 in the "paintbrush.v" from "disabled: disabled" to "disabled: p.disabled"

```
C:/prog/v/v_test/main.v:6:5: error: unknown field `style` in struct literal of type `rgbcube.color.BrushParams`.
Did you mean `styles`?
    4 |     fg: color.rgb(0, 0, 0)
    5 |     bg: color.hex(0xffffff)
    6 |     style: [color.bold, color.underline, color.italic]
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    7 | )
```
Solution: correct the name of the structure field in the example
```
C:/Users/zerg17/.vmodules/rgbcube/color/src/paintbrush.v:33:9: error: cannot take the address of rgbcube.color.new_brush(p)
   31 | 
   32 | pub fn new_brush_pointer(p BrushParams) &Brush {
   33 |     return &new_brush(p)
      |            ^
   34 | }
   35 |
```
I don't know how to fix it

**Comment by RGBCube** [comment]
Good find 🤔 Weird that the last one is invalid. Fixed in ##66 (not the last one though, will see)

**Comment by RGBCube** [comment]
Should be fixed in https://github.com/RGBCube/color.v/commit/d820ca3501053772549ed3bba8682b5d09c40934

**Comment by Zerg17** [comment]
The error has changed, but it's still in the same place. Why is it necessary to use a pointer there?
```
C:/Users/zerg17/.vmodules/rgbcube/color/src/paintbrush.v:33:10: notice: interface field `rgbcube.color.BrushImpl.fg` must be initialized
   31 | 
   32 | pub fn new_brush_pointer(p BrushParams) &Brush {
   33 |     return &BrushImpl{
      |             ~~~~~~~~~~
   34 |         ...new_brush(p)
   35 |     }
```

**Comment by RGBCube** [comment]
hmm, weird, also it needs a pointer since the method will return a pointer

**Comment by RGBCube** [comment]
i think i can't do this as new brush returns an interface

**Comment by Zerg17** [comment]
In the example from the documentation, an array of interfaces is created and pointers are not used. I don't see the point in them. https://github.com/vlang/v/blob/master/doc/docs.md#interfaces

**Comment by RGBCube** [comment]
Oh, i forgot to make the render method use a pointer, could you PR that? and bump the version

**Comment by RGBCube** [comment]
Oh, i forgot to make the render method use a pointer, could you PR that? and bump the version
